### ISSUE TITLE
Change the time in flextime.Now()?

### ISSUE THREAD

**Issue by d-tsuji** [Songmu/flextime#15]
I often use flextime in my work with production test code. Thanks.

I have one question.

In the test file, I use `flextime.Fix()` to fix the time, but using `flextime.After()` changes the time that can be obtained by `flextime.Now()`.

Is this a flextime spec?

```go
package main

import (
	"log"
	"testing"
	"time"

	"github.com/Songmu/flextime"
)

func TestHoge(t *testing.T) {
	testtime := time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)
	flextime.Fix(testtime)
	Hoge()
}

func Hoge() {
	deadline := flextime.Now().Add(1 * time.Hour)
	flextime.After(flextime.Until(deadline))

	log.Printf("now: %v", flextime.Now())
	log.Printf("now: %v", flextime.Now())
}
```

https://play.golang.org/p/dYzR1DUo5wB

```
=== RUN   TestHoge
2009/11/10 23:00:00 now: 2020-01-01 00:00:00 +0000 UTC
2009/11/10 23:00:00 now: 2020-01-01 01:00:00 +0000 UTC
--- PASS: TestHoge (0.00s)
PASS
```

**Comment by Songmu** [comment]
@d-tsuji 
Sorry for my slow response.

Yes. This is the intended specification.
Fix fixes the time and is not affected by the actual passage of time in the test code, but it does reflect the passage of time due to flextime.Sleep, etc.

This is beneficial when we want to test scenarios over some time schedule, as they are not affected by the actual time passage.

**Comment by d-tsuji** [comment]
@Songmu 
Thank you for answering my question. I understood that the time `t` field of the `fixedNS` struct, which can be retrieved with `flextime.Fix()`, is updated by `Sleep()`.

https://github.com/Songmu/flextime/blob/9a07487bf61b03c6f8d7640c1c37b0b22ff87107/fix.go#L8-L32

And the internal implementation of using `flextime.Until()` is that `send()` is called, and `Sleep()` is called by goroutine.

https://github.com/Songmu/flextime/blob/9a07487bf61b03c6f8d7640c1c37b0b22ff87107/faketimer.go#L63-L90

In the current implementation, `Reset` does not wait for the goroutine of `send` to finish. 

https://github.com/Songmu/flextime/blob/9a07487bf61b03c6f8d7640c1c37b0b22ff87107/faketimer.go#L92-L109

So, I understood that if `flextime.Until()` is used, the time retrieved by `flextime.Fix()` is runtime dependent Is this correct?

**Comment by d-tsuji** [comment]
> So, I understood that if `flextime.Until()` is used, the time retrieved by `flextime.Fix()` is runtime dependent Is this correct?

I was wrong. There is no problem if I implement it correctly to get the value from the channel.

For example, the following.

```go
package main

import (
	"log"
	"testing"
	"time"

	"github.com/Songmu/flextime"
)

func TestHoge(t *testing.T) {
	testtime := time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)
	flextime.Fix(testtime)
	Hoge()
}

func Hoge() {
	deadline := flextime.Now().Add(1 * time.Hour)
	<-flextime.After(flextime.Until(deadline))

	log.Printf("now: %v", flextime.Now())
	log.Printf("now: %v", flextime.Now())
}
```

```
=== RUN   TestHoge
2009/11/10 23:00:00 now: 2020-01-01 01:00:00 +0000 UTC
2009/11/10 23:00:00 now: 2020-01-01 01:00:00 +0000 UTC
--- PASS: TestHoge (0.00s)
PASS
```
