### ISSUE TITLE
question: mutex performance

### ISSUE THREAD

**Issue by johejo** [Songmu/flextime#8]
This library protects the backend with a package-level mutex, how is the performance impact?
Are there any use cases that we can't recommend flextime?

**Comment by Songmu** [comment]
Thanks for the question.

Actually, the time acquisition itself is not too low-cost process, so the overhead of flextime will not be a big deal.

I've added a benchmark in #9, and here are the results. The overhead is about this level, so it won't be much of a problem.


```console
$ go test -bench . -benchmem                                                                                              
goos: darwin
goarch: amd64
pkg: github.com/Songmu/flextime
BenchmarkFlextime_Now-8                 13926559                83.9 ns/op             0 B/op          0 allocs/op
BenchmarkStd_Now-8                      17668424                68.3 ns/op             0 B/op          0 allocs/op
BenchmarkFlextime_Now_concur-8           5111466               204 ns/op               0 B/op          0 allocs/op
BenchmarkStd_Now_concur-8                5730296               202 ns/op               0 B/op          0 allocs/op
PASS
ok      github.com/Songmu/flextime      5.303s
```

**Comment by johejo** [comment]
Great thanks.
This package makes testing about std time pkg a lot easier. :clap:
